// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QalatAldhaman.Store.Api.Data;

#nullable disable

namespace QalatAldhaman.Store.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806210628_AddProductPackageAvailabilityAndItemQuantity")]
    partial class AddProductPackageAvailabilityAndItemQuantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_seq");

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsCash")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_cash");

                    b.Property<bool>("AllowsDailyInstallment")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_daily_installment");

                    b.Property<bool>("AllowsMonthlyInstallment")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_monthly_installment");

                    b.Property<bool>("AllowsMonthlyRafidain")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_monthly_rafidain");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("HasCustomProductField")
                        .HasColumnType("boolean")
                        .HasColumnName("has_custom_product_field");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MinInvoiceCash")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_invoice_cash");

                    b.Property<decimal?>("MinInvoiceInstallment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_invoice_installment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresShopOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_shop_owner");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<bool>("UsesPackages")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_packages");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_governorates");

                    b.ToTable("governorates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "بغداد الكرخ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "بغداد الرصافة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "النجف الأشرف"
                        },
                        new
                        {
                            Id = 4,
                            Name = "البصرة"
                        },
                        new
                        {
                            Id = 5,
                            Name = "كربلاء"
                        },
                        new
                        {
                            Id = 6,
                            Name = "بابل"
                        },
                        new
                        {
                            Id = 7,
                            Name = "سماوة (المثنى)"
                        },
                        new
                        {
                            Id = 8,
                            Name = "الناصرية"
                        },
                        new
                        {
                            Id = 9,
                            Name = "الديوانية"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ديالى"
                        },
                        new
                        {
                            Id = 11,
                            Name = "الموصل"
                        },
                        new
                        {
                            Id = 12,
                            Name = "كركوك"
                        });
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomProductDescription")
                        .HasColumnType("text")
                        .HasColumnName("custom_product_description");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<decimal?>("DownPaymentSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("down_payment_snapshot");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("integer")
                        .HasColumnName("governorate_id");

                    b.Property<decimal?>("GpsLat")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("gps_lat");

                    b.Property<decimal?>("GpsLng")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("gps_lng");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("text")
                        .HasColumnName("home_address");

                    b.Property<decimal?>("InstallmentPaymentAmountSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("installment_payment_amount_snapshot");

                    b.Property<string>("MediaType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("NearestLandmark")
                        .HasColumnType("text")
                        .HasColumnName("nearest_landmark");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("PurchaseMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purchase_method");

                    b.Property<string>("ShopAddress")
                        .HasColumnType("text")
                        .HasColumnName("shop_address");

                    b.Property<string>("ShopName")
                        .HasColumnType("text")
                        .HasColumnName("shop_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPriceSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_price_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_orders_category_id");

                    b.HasIndex("GovernorateId")
                        .HasDatabaseName("ix_orders_governorate_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_number");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_orders_package_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_orders_product_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitDownPaymentSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_down_payment_snapshot");

                    b.Property<decimal?>("UnitPeriodicPaymentSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_periodic_payment_snapshot");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CashPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cash_price");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("DailyPaymentAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("daily_payment_amount");

                    b.Property<decimal?>("DailyTotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("daily_total_price");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinimumTotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("minimum_total_price");

                    b.Property<decimal?>("MonthlyDownPayment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_down_payment");

                    b.Property<decimal?>("MonthlyPaymentAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_payment_amount");

                    b.Property<decimal?>("MonthlyTotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_total_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("RafidainDownPayment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rafidain_down_payment");

                    b.Property<decimal?>("RafidainPaymentAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rafidain_payment_amount");

                    b.Property<decimal?>("RafidainTotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rafidain_total_price");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_packages_category_id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CashPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cash_price");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DailyPaymentAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("daily_payment_amount");

                    b.Property<decimal?>("DailyTotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("daily_total_price");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailableInPackages")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available_in_packages");

                    b.Property<decimal?>("MonthlyDownPayment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_down_payment");

                    b.Property<decimal?>("MonthlyPaymentAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_payment_amount");

                    b.Property<decimal?>("MonthlyTotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_total_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("RafidainDownPayment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rafidain_down_payment");

                    b.Property<decimal?>("RafidainPaymentAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rafidain_payment_amount");

                    b.Property<decimal?>("RafidainTotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rafidain_total_price");

                    b.Property<string>("SKU")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_images");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_images_product_id");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.PurchaseMethodContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractPdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("contract_pdf_url");

                    b.Property<string>("PurchaseMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purchase_method");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_purchase_method_contracts");

                    b.HasIndex("PurchaseMethod")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_method_contracts_purchase_method");

                    b.ToTable("purchase_method_contracts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PurchaseMethod = "Cash",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            PurchaseMethod = "MonthlyInstallment",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            PurchaseMethod = "MonthlyRafidain",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            PurchaseMethod = "DailyInstallment",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_reviews_product_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Order", b =>
                {
                    b.HasOne("QalatAldhaman.Store.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_categories_category_id");

                    b.HasOne("QalatAldhaman.Store.Api.Entities.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_governorates_governorate_id");

                    b.HasOne("QalatAldhaman.Store.Api.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_packages_package_id");

                    b.HasOne("QalatAldhaman.Store.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_products_product_id");

                    b.Navigation("Category");

                    b.Navigation("Governorate");

                    b.Navigation("Package");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.OrderItem", b =>
                {
                    b.HasOne("QalatAldhaman.Store.Api.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("QalatAldhaman.Store.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Package", b =>
                {
                    b.HasOne("QalatAldhaman.Store.Api.Entities.Category", "Category")
                        .WithMany("Packages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_packages_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Product", b =>
                {
                    b.HasOne("QalatAldhaman.Store.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.ProductImage", b =>
                {
                    b.HasOne("QalatAldhaman.Store.Api.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_images_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Review", b =>
                {
                    b.HasOne("QalatAldhaman.Store.Api.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Category", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QalatAldhaman.Store.Api.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
